### ISSUE TITLE
Errors in project-level output mapping (OC and Infrastructure)

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/infrastructure#35]
* [ ] 1. 'owner' -> 'publicAuthority' (there is no 'owner' code) [multiple occurrences]
* [x] 2. `location` -> `locations`
* [x] 3. `gazetter` -> `gazetteer`
* [x] 4. 'scope' -> 'projectScope' (there is no 'scope' code) [multiple occurrences]
* [ ] 5. 'funder' is in the OCDS codelist, but not in the PPP codelist used by this repo
* [x] 6. 'budgetApproval' doesn't exist in any codelist

**Comment by duncandewhurst** [comment]
1 and 5 depend on the resolution to #43

2, 3 and 4 have been addressed in the mapping Google Sheet

6 is addressed in https://github.com/open-contracting/infrastructure/pull/44

**Comment by jpmckinney** [comment]
Google Sheet is at https://docs.google.com/spreadsheets/d/1tpXKCrNY1vUEPo6O1j-GPhxgSna7CZ5uwz_eTNLEOr8/edit?disco=AAAACXYu96c&ts=5bfead07#gid=0

**Comment by jpmckinney** [comment]
Re: #43, (1) is my suggestion to change 'owner' to 'publicAuthority'. 'owner' occurs in neither OCDS nor PPPs.

**Comment by duncandewhurst** [comment]
The definition of 'publicAuthority' is currently PPP specific:

> The unit/body/department within a government that is tendering and contracting the project. The public counterpart in the PPP contract.

Moving this issue to the beta milestone in line with #43

**Comment by jpmckinney** [comment]
Given that the only issues remaining are those in #43, I think we can close this issue (and copy your comment about publicAuthority there).
